### ISSUE TITLE
Create and validate a schema for test db

### ISSUE THREAD

**Issue by aPruner** [DarienFlamont/ExerciseAppBackend#7]
We need to actually build a data schema with which to enforce our data models. Looks like we can do this on the mongodb atlas UI: https://docs.mongodb.com/stitch/mongodb/enforce-a-document-schema/

**Comment by DarienFlamont** [comment]
We are likely going to do this in python and validate using some sort of model.
- Validation using models
- Create python schemas (user, workout, etc.)

**Comment by DarienFlamont** [comment]
https://www.codementor.io/@shreybatra/working-with-structured-data-with-mongodb-in-django-part-1-kwbp7fn90

**Comment by DarienFlamont** [comment]
We changed the scope of this schema issue into just a user schema which has been completed under Models.py in the ExerciseAppBackend folder.  New issues will be opened for other DB schemas.
